### ISSUE TITLE
Unrecognized manifest key 'browser_specific_settings' in Chromium-based browsers

### ISSUE THREAD

**Issue by huyhoang-mike** [phawdk/studydrive-download#1]
For those people who encountered this notification when importing this extension in Chromium-based browsers, please just simply remove the **browser_specific_settings** section from your manifest.json file. The manifest key browser_specific_settings is not being used by Chrome, only by Firefox. 

![image](https://github.com/user-attachments/assets/0ebefca9-5713-4050-ba1a-b3e015902fba)

It's just a warning, not an error. You can keep using the extension without any problems :)

**Comment by phawdk** [comment]
Thanks for pointing this out! I’ve updated the README to mention that if you’re using a Chromium-based browser, you can ignore the `browser_specific_settings` warning.

Appreciate you sharing the tip!
