### ISSUE TITLE
Uncaught TypeError: Cannot create proxy with a non-object as target or handler

### ISSUE THREAD

**Issue by patrickbenkoe** [phawdk/studydrive-download#3]
hey team,

i get that error after clicking the download button
"Uncaught TypeError: Cannot create proxy with a non-object as target or handler"

Stacktrace
content-script.js:20 (Anonyme Funktion)

    {},
    {
      set(target, prop, value, receiver) {
        if (prop === "user") {
          value = new Proxy(value, user_proxy_handler);   **<--- Thats marked yellow**
        }
        return Reflect.set(target, prop, value, receiver);
      },
    }
  );

BR

**Comment by patrickbenkoe** [comment]
did it and:

Non-object value assigned to user property: null
Kontext
https://www.studydrive.net/de/
Stacktrace
content-script.js:23 (set)
https://www.studydrive.net/de/:21 (Anonyme Funktion)

if (prop === "user") {
          if (value && typeof value === 'object') {
            value = new Proxy(value, user_proxy_handler);
          } else {
            console.warn("Non-object value assigned to user property:", value); <---- thats now yellow
          }
        }
        return Reflect.set(target, prop, value, receiver);
      },
    }

:-) BR

**Comment by phawdk** [comment]
Hi,

intresting, thx!
It did not work correct? Did the buttons show up?

Which browser are you using? Perhaps I can try to reproduce it myself.
In the meantime you can also try to use a different browser in case you need something downloaded.

Which version of the Browser are you using?

Perhaps also try to disable all other extensions once.

BS :)

**Comment by patrickbenkoe** [comment]
Using Chrome with no extensions for that. Buttons are showing, but thats it.
Is it, because the file is .docx?
Try it: [Link](https://www.studydrive.net/de/doc/schema-zur-losung-von-fallbeispielen-rewi8850/1884201)

**Comment by phawdk** [comment]
Glad it works, I will change it for everyone now.
The message `Non-object value assigned to user property: null` poses not a problem, as long as the download/open buttons work.

Thank you for reporting this bug, happy studying!
