### ISSUE TITLE
Does not work anymore (could not reproduce)

### ISSUE THREAD

**Issue by AJLUNL** [phawdk/studydrive-download#4]

**Comment by phawdk** [comment]
Hello, could you please tell me which browser you are using? What happens and what do you expect to happen?
I've just checked myself, it does in fact still work for me. You need to be logged in to studydrive for this to work.

Do the buttons show up?
If they do, does something happen when you click them?

Could you please check the console and see if there is any error or warning?

**Comment by AJLUNL** [comment]
Hey,
thank you very much for the extension, Indeed it is working I was not logged in!
tried to delete the issue but failed...



Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by phawdk** [comment]
Thank you for the reply. Don't worry about deleting this issue, i will close it now.

I'll also add a note to the ReadMe that one needs to be logged in for this to work to prevent this from happening to other users.

Have a nice day 👋
